error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T16:50:51.340Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:16:37.904Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:17:39.692Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:17:50.621Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:18:39.062Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:19:42.278Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:19:48.751Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:19:53.584Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:06.406Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:09.321Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:21.613Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:23.841Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:32.612Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:33.512Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:40.029Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:40.900Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:48.326Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:20:51.800Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:21:01.438Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:21:11.619Z"}
error: error connectibg redis  connect ECONNREFUSED ::1:6379 {"address":"::1","code":"ECONNREFUSED","errno":-4078,"port":6379,"stack":"Error: connect ECONNREFUSED ::1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","syscall":"connect","timestamp":"2023-08-12T17:21:27.876Z"}
error: Error authenticating Postgress Db object is not iterable (cannot read property Symbol(Symbol.iterator)) {"stack":"TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))\n    at connect (D:\\esa\\backend\\index.js:47:33)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:67:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-12T17:46:26.319Z"}
error: Error authenticating Postgress Db object is not iterable (cannot read property Symbol(Symbol.iterator)) {"stack":"TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))\n    at connect (D:\\esa\\backend\\index.js:47:33)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:73:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-12T17:47:18.178Z"}
error: error connectibg redis  The client is closed {"stack":"Error: The client is closed\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:490:31)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:50:45)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:102:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-15T06:50:05.321Z"}
error: error connectibg redis  The client is closed {"stack":"Error: The client is closed\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:490:31)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:50:44)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:102:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-15T06:50:15.887Z"}
error: error connectibg redis  The client is closed {"stack":"Error: The client is closed\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:490:31)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:50:44)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:102:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-15T06:50:46.339Z"}
error: error connectibg redis  The client is closed {"stack":"Error: The client is closed\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:490:31)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:50:44)\n    at Server.<anonymous> (D:\\esa\\backend\\index.js:102:5)\n    at Object.onceWrapper (node:events:627:28)\n    at Server.emit (node:events:513:28)\n    at emitListeningNT (node:net:1774:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)","timestamp":"2023-08-15T06:51:15.802Z"}
error: error connectibg redis  Invalid argument type {"stack":"TypeError: Invalid argument type\n    at encodeCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\RESP2\\encoder.js:17:19)\n    at RedisCommandsQueue.getCommandToSend (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\commands-queue.js:138:45)\n    at Commander._RedisClient_tick (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:515:76)\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:502:82)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:54:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-08-15T06:52:12.811Z"}
error: error connectibg redis  Invalid argument type {"stack":"TypeError: Invalid argument type\n    at encodeCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\RESP2\\encoder.js:17:19)\n    at RedisCommandsQueue.getCommandToSend (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\commands-queue.js:138:45)\n    at Commander._RedisClient_tick (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:515:76)\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:502:82)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:54:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-08-15T06:52:21.059Z"}
error: error connectibg redis  Invalid argument type {"stack":"TypeError: Invalid argument type\n    at encodeCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\RESP2\\encoder.js:17:19)\n    at RedisCommandsQueue.getCommandToSend (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\commands-queue.js:138:45)\n    at Commander._RedisClient_tick (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:515:76)\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:502:82)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:54:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-08-15T06:52:55.206Z"}
error: error connectibg redis  Invalid argument type {"stack":"TypeError: Invalid argument type\n    at encodeCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\RESP2\\encoder.js:17:19)\n    at RedisCommandsQueue.getCommandToSend (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\commands-queue.js:138:45)\n    at Commander._RedisClient_tick (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:515:76)\n    at Commander._RedisClient_sendCommand (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:502:82)\n    at Commander.commandsExecutor (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\client\\index.js:188:154)\n    at BaseClass.<computed> [as auth] (D:\\esa\\backend\\node_modules\\@redis\\client\\dist\\lib\\commander.js:8:29)\n    at connectToRedisStore (D:\\esa\\backend\\index.js:54:44)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-08-15T06:52:57.579Z"}
error: Error authenticating Postgress Db The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined {"code":"ERR_INVALID_ARG_TYPE","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n    at new NodeError (node:internal/errors:399:5)\n    at Hash.update (node:internal/crypto/hash:109:11)\n    at users.beforeFind (D:\\esa\\backend\\app\\models\\users.js:41:61)\n    at users.runHooks (D:\\esa\\backend\\node_modules\\sequelize\\lib\\hooks.js:96:18)\n    at users.findAll (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1113:18)\n    at users.findOne (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1240:23)\n    at users.findOrCreate (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1411:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connect (D:\\esa\\backend\\index.js:77:33)","timestamp":"2023-08-15T07:28:56.100Z"}
error: Error authenticating Postgress Db The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined {"code":"ERR_INVALID_ARG_TYPE","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n    at new NodeError (node:internal/errors:399:5)\n    at Hash.update (node:internal/crypto/hash:109:11)\n    at users.beforeFind (D:\\esa\\backend\\app\\models\\users.js:41:61)\n    at users.runHooks (D:\\esa\\backend\\node_modules\\sequelize\\lib\\hooks.js:96:18)\n    at users.findAll (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1113:18)\n    at users.findOne (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1240:23)\n    at users.findOrCreate (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1411:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connect (D:\\esa\\backend\\index.js:77:33)","timestamp":"2023-08-15T07:29:19.272Z"}
error: Error authenticating Postgress Db The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined {"code":"ERR_INVALID_ARG_TYPE","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n    at new NodeError (node:internal/errors:399:5)\n    at Hash.update (node:internal/crypto/hash:109:11)\n    at users.beforeFind (D:\\esa\\backend\\app\\models\\users.js:41:61)\n    at users.runHooks (D:\\esa\\backend\\node_modules\\sequelize\\lib\\hooks.js:96:18)\n    at users.findAll (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1113:18)\n    at users.findOne (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1240:23)\n    at users.findOrCreate (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1411:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connect (D:\\esa\\backend\\index.js:77:33)","timestamp":"2023-08-15T07:30:07.083Z"}
error: Error authenticating Postgress Db SUCCESS {"data":"User Found","description":"SUCCESS","stack":"Error: SUCCESS\n    at connect (D:\\esa\\backend\\index.js:92:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","statusCode":200,"timestamp":"2023-08-15T07:39:24.342Z"}
error: Error authenticating Postgress Db relation "users" does not exist {"name":"SequelizeDatabaseError","original":{"code":"42P01","file":"parse_relation.c","length":104,"line":"1381","name":"error","position":"94","routine":"parserOpenTable","severity":"ERROR","sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;"},"parameters":{},"parent":{"code":"42P01","file":"parse_relation.c","length":104,"line":"1381","name":"error","position":"94","routine":"parserOpenTable","severity":"ERROR","sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;"},"sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;","stack":"Error\n    at Query.run (D:\\esa\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at D:\\esa\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.select (D:\\esa\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:407:12)\n    at async users.findAll (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1140:21)\n    at async users.findOne (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1240:12)\n    at async users.findOrCreate (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1411:21)\n    at async connect (D:\\esa\\backend\\index.js:79:33)","timestamp":"2023-08-15T07:39:34.160Z"}
error: Error authenticating Postgress Db relation "users" does not exist {"name":"SequelizeDatabaseError","original":{"code":"42P01","file":"parse_relation.c","length":104,"line":"1381","name":"error","position":"94","routine":"parserOpenTable","severity":"ERROR","sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;"},"parameters":{},"parent":{"code":"42P01","file":"parse_relation.c","length":104,"line":"1381","name":"error","position":"94","routine":"parserOpenTable","severity":"ERROR","sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;"},"sql":"SELECT \"id\", \"name\", \"email\", \"password\", \"role\", \"createdAt\", \"updatedAt\", \"deletedAt\" FROM \"users\" AS \"users\" WHERE (\"users\".\"deletedAt\" IS NULL AND \"users\".\"name\" = 'admin') LIMIT 1;","stack":"Error\n    at Query.run (D:\\esa\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at D:\\esa\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.select (D:\\esa\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:407:12)\n    at async users.findAll (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1140:21)\n    at async users.findOne (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1240:12)\n    at async users.findOrCreate (D:\\esa\\backend\\node_modules\\sequelize\\lib\\model.js:1411:21)\n    at async connect (D:\\esa\\backend\\index.js:79:33)","timestamp":"2023-08-15T07:41:53.445Z"}
